project:
  type: book
  output-dir: docs

book:
  title: "Probabilistic Generative Modeling Notes"
  author: "Bilal Ahmed"
  chapters:
    - index.qmd
    - part: "Background"
      chapters:
        # - background/notation.qmd
        - background/basics.qmd
        # - background/score-matching.qmd
    - part: "Diffusion Models"
      chapters:
        # - diffusion/score-matching.qmd
        - diffusion/ddpm.qmd
        - diffusion/edm.qmd
        # - diffusion/summary.qmd
    # - part: "Flow Matching"
    #   chapters:
    #     - flows/flow-matching.qmd
    # - part: "Image Restoration"
    #   chapters:
    #     - image-restoration/intro.qmd
    - references.qmd

bibliography: 
  - references.bib
  - diffusion.bib

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  # pdf:
  #   documentclass: scrreprt